### PR TITLE
6주차 과제 제출 - 전창기

### PR DESCRIPTION
**Pull request by ChanggiJeon**
### PR 올리기 전에 확인사항

1. head barnch와 sync를 맞춰주세요.

```bash
$ git pull https://github.com/hanghae-plus/front_2nd.git main
```

2. base branch를 `hanghae-plus:main`이 아니라 `hanghae-plus:<본안아이디>` 로 수정해주세요 확인해주세요.

### CODE REVIEW

**Comment by spartacontents** [comment]
ESLint Results:


/home/runner/work/front_2nd/front_2nd/packages/assignment-6/src/components/AdminPage.tsx
  7:21  error  'updatedProduct' is defined but never used  no-unused-vars
  8:18  error  'newProduct' is defined but never used      no-unused-vars
  9:17  error  'newCoupon' is defined but never used       no-unused-vars

/home/runner/work/front_2nd/front_2nd/packages/assignment-6/src/forLintError.ts
  2:3  error  'console' is not defined  no-undef

/home/runner/work/front_2nd/front_2nd/packages/assignment-6/src/main.tsx
  4:10  error  'forLintError' is defined but never used  no-unused-vars
  7:21  error  'document' is not defined                 no-undef

✖ 6 problems (6 errors, 0 warnings)

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 57 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 5.8s |
| 🔴  largest contentful paint | 9.1s |
| 🔴  interactive | 9.3s |
| 🟢  total blocking time | 200.0ms |
| 🟢  cumulative layout shift | 0.0 |

**Review by jung-han — APPROVED** [review]
일부러 실패케이스를 만들어서 올리신 것 처럼 보이네요!
액션은 잘 동작하는 것처럼 보입니다. 고생하셨어요~

**Pull request merged**
