### PR TITLE
6주차 과제 제출 - 전창기

### PR DESCRIPTION
**Pull request by ChanggiJeon**
### PR 올리기 전에 확인사항

1. head barnch와 sync를 맞춰주세요.

```bash
$ git pull https://github.com/hanghae-plus/front_2nd.git main
```

2. base branch를 `hanghae-plus:main`이 아니라 `hanghae-plus:<본안아이디>` 로 수정해주세요 확인해주세요.

### CODE REVIEW

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
@님, 리뷰를 부탁드립니다.

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
@mh0223님, 리뷰를 부탁드립니다.

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by mh0223** [comment]
> @mh0223님, 리뷰를 부탁드립니다.

굳!

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
ESLint Results:


> assignment-6@0.0.0 lint /home/runner/work/front_2nd/front_2nd/packages/assignment-6
> eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0

Invalid option '--ext' - perhaps you meant '-c'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
/home/runner/work/front_2nd/front_2nd/packages/assignment-6:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  assignment-6@0.0.0 lint: `eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0`
Exit status 2

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
ESLint Results:


> assignment-6@0.0.0 lint /home/runner/work/front_2nd/front_2nd/packages/assignment-6
> eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0

Invalid option '--ext' - perhaps you meant '-c'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  assignment-6@0.0.0 lint: `eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0`
Exit status 2

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
ESLint Results:


> assignment-6@0.0.0 lint /home/runner/work/front_2nd/front_2nd/packages/assignment-6
> eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0

Invalid option '--ext' - perhaps you meant '-c'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  assignment-6@0.0.0 lint: `eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0`
Exit status 2

**Comment by spartacontents** [comment]
ESLint Results:


> assignment-6@0.0.0 lint /home/runner/work/front_2nd/front_2nd/packages/assignment-6
> eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0

Invalid option '--ext' - perhaps you meant '-c'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  assignment-6@0.0.0 lint: `eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0`
Exit status 2

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
ESLint Results:


> assignment-6@0.0.0 lint /home/runner/work/front_2nd/front_2nd/packages/assignment-6
> eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0

Invalid option '--ext' - perhaps you meant '-c'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  assignment-6@0.0.0 lint: `eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0`
Exit status 2

**Comment by spartacontents** [comment]
ESLint Results:


> assignment-6@0.0.0 lint /home/runner/work/front_2nd/front_2nd/packages/assignment-6
> eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0

Invalid option '--ext' - perhaps you meant '-c'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  assignment-6@0.0.0 lint: `eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0`
Exit status 2

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
ESLint Results:


> assignment-6@0.0.0 lint /home/runner/work/front_2nd/front_2nd/packages/assignment-6
> eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0

Invalid option '--ext' - perhaps you meant '-c'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  assignment-6@0.0.0 lint: `eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0`
Exit status 2

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
ESLint Results:


> assignment-6@0.0.0 lint /home/runner/work/front_2nd/front_2nd/packages/assignment-6
> eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0

Invalid option '--ext' - perhaps you meant '-c'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  assignment-6@0.0.0 lint: `eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0`
Exit status 2

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 54 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 6.3s |
| 🔴  largest contentful paint | 9.5s |
| 🔴  interactive | 9.8s |
| 🟢  total blocking time | 276.7ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
ESLint Results:


> assignment-6@0.0.0 lint /home/runner/work/front_2nd/front_2nd/packages/assignment-6
> eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0

Invalid option '--ext' - perhaps you meant '-c'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  assignment-6@0.0.0 lint: `eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0`
Exit status 2

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 53 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 6.0s |
| 🔴  largest contentful paint | 9.3s |
| 🔴  interactive | 9.7s |
| 🟠  total blocking time | 363.3ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 61 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 5.7s |
| 🔴  largest contentful paint | 9.0s |
| 🔴  interactive | 9.1s |
| 🟢  total blocking time | 66.7ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
ESLint Results:


> assignment-6@0.0.0 lint /home/runner/work/front_2nd/front_2nd/packages/assignment-6
> eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0

Invalid option '--ext' - perhaps you meant '-c'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  assignment-6@0.0.0 lint: `eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0`
Exit status 2

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 52 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 5.8s |
| 🔴  largest contentful paint | 9.0s |
| 🔴  interactive | 9.5s |
| 🟢  total blocking time | 43.7ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
ESLint Results:


> assignment-6@0.0.0 lint /home/runner/work/front_2nd/front_2nd/packages/assignment-6
> eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0 "--" "--no-eslintrc" "-c" "./packages/assignment-6/.eslintrc.js"

Invalid option '--ext' - perhaps you meant '-c'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  assignment-6@0.0.0 lint: `eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0 "--" "--no-eslintrc" "-c" "./packages/assignment-6/.eslintrc.js"`
Exit status 2

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 61 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 5.7s |
| 🔴  largest contentful paint | 9.0s |
| 🔴  interactive | 9.1s |
| 🟢  total blocking time | 70.0ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 61 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 5.7s |
| 🔴  largest contentful paint | 9.0s |
| 🔴  interactive | 9.1s |
| 🟢  total blocking time | 66.7ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
ESLint Results:


> assignment-6@0.0.0 lint /home/runner/work/front_2nd/front_2nd/packages/assignment-6
> eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0

Invalid option '--ext' - perhaps you meant '-c'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
 ELIFECYCLE  Command failed with exit code 2.

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 60 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 5.8s |
| 🔴  largest contentful paint | 9.0s |
| 🔴  interactive | 9.1s |
| 🟢  total blocking time | 73.3ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
ESLint Results:


> assignment-6@0.0.0 lint /home/runner/work/front_2nd/front_2nd/packages/assignment-6
> eslint . --config ./packages/assignment-6/.eslintrc.cjs --report-unused-disable-directives --max-warnings 0


Oops! Something went wrong! :(

ESLint: 8.57.0

Error: ENOENT: no such file or directory, stat '/home/runner/work/front_2nd/front_2nd/packages/assignment-6/packages/assignment-6/.eslintrc.cjs'
    at async Object.stat (node:internal/fs/promises:1032:18)
    at async loadFlatConfigFile (/home/runner/work/front_2nd/front_2nd/node_modules/.pnpm/eslint@8.57.0/node_modules/eslint/lib/eslint/flat-eslint.js:272:20)
    at async calculateConfigArray (/home/runner/work/front_2nd/front_2nd/node_modules/.pnpm/eslint@8.57.0/node_modules/eslint/lib/eslint/flat-eslint.js:382:28)
    at async FlatESLint.lintFiles (/home/runner/work/front_2nd/front_2nd/node_modules/.pnpm/eslint@8.57.0/node_modules/eslint/lib/eslint/flat-eslint.js:745:25)
    at async Object.execute (/home/runner/work/front_2nd/front_2nd/node_modules/.pnpm/eslint@8.57.0/node_modules/eslint/lib/cli.js:421:23)
    at async main (/home/runner/work/front_2nd/front_2nd/node_modules/.pnpm/eslint@8.57.0/node_modules/eslint/bin/eslint.js:152:22)
/home/runner/work/front_2nd/front_2nd/packages/assignment-6:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  assignment-6@0.0.0 lint: `eslint . --config ./packages/assignment-6/.eslintrc.cjs --report-unused-disable-directives --max-warnings 0`
Exit status 2

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 57 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 5.9s |
| 🔴  largest contentful paint | 9.1s |
| 🔴  interactive | 9.3s |
| 🟢  total blocking time | 193.3ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 52 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 6.1s |
| 🔴  largest contentful paint | 9.4s |
| 🔴  interactive | 9.8s |
| 🟢  total blocking time | 47.0ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 61 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 5.7s |
| 🔴  largest contentful paint | 9.0s |
| 🔴  interactive | 9.1s |
| 🟢  total blocking time | 66.7ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 57 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 5.8s |
| 🔴  largest contentful paint | 9.1s |
| 🔴  interactive | 9.3s |
| 🟢  total blocking time | 173.3ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 61 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 5.7s |
| 🔴  largest contentful paint | 9.0s |
| 🔴  interactive | 9.1s |
| 🟢  total blocking time | 70.0ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 56 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 6.0s |
| 🔴  largest contentful paint | 9.2s |
| 🔴  interactive | 9.4s |
| 🟢  total blocking time | 206.7ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 61 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 5.7s |
| 🔴  largest contentful paint | 9.0s |
| 🔴  interactive | 9.1s |
| 🟢  total blocking time | 70.0ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 61 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 5.7s |
| 🔴  largest contentful paint | 9.0s |
| 🔴  interactive | 9.1s |
| 🟢  total blocking time | 70.0ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 57 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 5.9s |
| 🔴  largest contentful paint | 9.2s |
| 🔴  interactive | 9.4s |
| 🟢  total blocking time | 186.7ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 54 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 5.9s |
| 🔴  largest contentful paint | 9.2s |
| 🔴  interactive | 9.5s |
| 🟢  total blocking time | 283.3ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 56 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 5.8s |
| 🔴  largest contentful paint | 9.1s |
| 🔴  interactive | 9.3s |
| 🟢  total blocking time | 216.7ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 61 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 5.8s |
| 🔴  largest contentful paint | 9.0s |
| 🔴  interactive | 9.1s |
| 🟢  total blocking time | 56.7ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
ESLint Results:

Invalid option '--ext' - perhaps you meant '-c'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 57 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 5.8s |
| 🔴  largest contentful paint | 9.1s |
| 🔴  interactive | 9.3s |
| 🟢  total blocking time | 180.0ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
ESLint Results:


Oops! Something went wrong! :(

ESLint: 8.57.0

A config object is using the "root" key, which is not supported in flat config system.

Flat configs always act as if they are the root config file, so this key can be safely removed.

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 55 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 5.9s |
| 🔴  largest contentful paint | 9.2s |
| 🔴  interactive | 9.5s |
| 🟢  total blocking time | 276.7ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
ESLint Results:


Oops! Something went wrong! :(

ESLint: 8.57.0

TypeError: Key "processor": Could not find "parser" in plugin "@typescript-eslint".
    at [finalizeConfig] (/home/runner/work/front_2nd/front_2nd/node_modules/.pnpm/eslint@8.57.0/node_modules/eslint/lib/config/flat-config-array.js:215:27)
    at FlatConfigArray.getConfig (/home/runner/work/front_2nd/front_2nd/node_modules/.pnpm/@humanwhocodes+config-array@0.11.14/node_modules/@humanwhocodes/config-array/api.js:938:55)
    at FlatConfigArray.isFileIgnored (/home/runner/work/front_2nd/front_2nd/node_modules/.pnpm/@humanwhocodes+config-array@0.11.14/node_modules/@humanwhocodes/config-array/api.js:962:15)
    at entryFilter (/home/runner/work/front_2nd/front_2nd/node_modules/.pnpm/eslint@8.57.0/node_modules/eslint/lib/eslint/eslint-helpers.js:320:47)
    at Object.isAppliedFilter (/home/runner/work/front_2nd/front_2nd/node_modules/.pnpm/@nodelib+fs.walk@1.2.8/node_modules/@nodelib/fs.walk/out/readers/common.js:12:31)
    at AsyncReader._handleEntry (/home/runner/work/front_2nd/front_2nd/node_modules/.pnpm/@nodelib+fs.walk@1.2.8/node_modules/@nodelib/fs.walk/out/readers/async.js:86:20)
    at /home/runner/work/front_2nd/front_2nd/node_modules/.pnpm/@nodelib+fs.walk@1.2.8/node_modules/@nodelib/fs.walk/out/readers/async.js:65:22
    at callSuccessCallback (/home/runner/work/front_2nd/front_2nd/node_modules/.pnpm/@nodelib+fs.scandir@2.1.5/node_modules/@nodelib/fs.scandir/out/providers/async.js:103:5)
    at /home/runner/work/front_2nd/front_2nd/node_modules/.pnpm/@nodelib+fs.scandir@2.1.5/node_modules/@nodelib/fs.scandir/out/providers/async.js:29:13
    at node:fs:187:23

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 53 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 5.8s |
| 🔴  largest contentful paint | 9.1s |
| 🔴  interactive | 9.5s |
| 🟢  total blocking time | 40.3ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
ESLint Results:


Oops! Something went wrong! :(

ESLint: 8.57.0

A config object is using the "env" key, which is not supported in flat config system.

Flat config uses "languageOptions.globals" to define global variables for your files.

Please see the following page for information on how to convert your config object into the correct format:
https://eslint.org/docs/latest/use/configure/migration-guide#configuring-language-options

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 58 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 5.8s |
| 🔴  largest contentful paint | 9.1s |
| 🔴  interactive | 9.3s |
| 🟢  total blocking time | 156.7ms |
| 🟢  cumulative layout shift | 0.0 |

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
빌드 실패 ❌

**Comment by spartacontents** [comment]
ESLint Results:


/home/runner/work/front_2nd/front_2nd/packages/assignment-6/src/components/AdminPage.tsx
  7:21  error  'updatedProduct' is defined but never used  no-unused-vars
  8:18  error  'newProduct' is defined but never used      no-unused-vars
  9:17  error  'newCoupon' is defined but never used       no-unused-vars

/home/runner/work/front_2nd/front_2nd/packages/assignment-6/src/forLintError.ts
  2:3  error  'console' is not defined  no-undef

/home/runner/work/front_2nd/front_2nd/packages/assignment-6/src/main.tsx
  4:10  error  'forLintError' is defined but never used  no-unused-vars
  7:21  error  'document' is not defined                 no-undef

✖ 6 problems (6 errors, 0 warnings)

**Comment by spartacontents** [comment]
테스트 성공 ✅

**Comment by spartacontents** [comment]
⚡️ Lighthouse Average Scores Across Reports:
| Category | Score |
| --- | --- |
| 🔴  performance | 60 |
| 🟠  accessibility | 84 |
| 🟢  best practices | 99 |
| 🟠  seo | 82 |
| 🔴  pwa | NaN |

⚡️ Average Details Across All Reports:
| Category | Score |
| --- | --- |
| 🔴  first contentful paint | 5.8s |
| 🔴  largest contentful paint | 9.0s |
| 🔴  interactive | 9.1s |
| 🟢  total blocking time | 80.0ms |
| 🟢  cumulative layout shift | 0.0 |

**Pull request closed without merging**
