### PR TITLE
6주차 과제 제출 - 안수빈

### PR DESCRIPTION
**Pull request by AnSuebin**
### PR 올리기 전에 확인사항

1. head barnch와 sync를 맞춰주세요.

```bash
$ git pull https://github.com/hanghae-plus/front_2nd.git main
```

2. base branch를 `hanghae-plus:main`이 아니라 `hanghae-plus:<본안아이디>` 로 수정해주세요 확인해주세요.

### CODE REVIEW

**Comment by spartacontents** [comment]
@lucettin5 has been randomly assigned to review this PR. Please take a look when you have a chance!

**Comment by spartacontents** [comment]
@Raihyul has been randomly assigned to review this PR. Please take a look when you have a chance!

**Comment by spartacontents** [comment]
@Raihyul has been randomly assigned to review this PR. Please take a look when you have a chance!

**Comment by spartacontents** [comment]
@Raihyul has been randomly assigned to review this PR. Please take a look when you have a chance!

**Comment by spartacontents** [comment]
@Raihyul has been randomly assigned to review this PR. Please take a look when you have a chance!

**Comment by spartacontents** [comment]
@Raihyul has been randomly assigned to review this PR. Please take a look when you have a chance!

**Comment by spartacontents** [comment]
@horang-e has been randomly assigned to review this PR. Please take a look when you have a chance!

**Comment by spartacontents** [comment]
@horang-e has been randomly assigned to review this PR. Please take a look when you have a chance!

**Comment by spartacontents** [comment]
@Raihyul has been randomly assigned to review this PR. Please take a look when you have a chance!

**Comment by spartacontents** [comment]
@horang-e has been randomly assigned to review this PR. Please take a look when you have a chance!

**Comment by spartacontents** [comment]
@lucettin5 has been randomly assigned to review this PR. Please take a look when you have a chance!

**Comment by spartacontents** [comment]
@lucettin5 has been randomly assigned to review this PR. Please take a look when you have a chance!

**Comment by spartacontents** [comment]
@Raihyul has been randomly assigned to review this PR. Please take a look when you have a chance!

**Comment by spartacontents** [comment]
### 커버리지 결과

  * 라인 커버리지: 82.58%
  * 브랜치 커버리지: 92.39%
  * 함수 커버리지: 86.95%
  * 구문 커버리지: 82.58%

**Comment by spartacontents** [comment]
### 커버리지 결과

  * 라인 커버리지: 82.58%
  * 브랜치 커버리지: 92.39%
  * 함수 커버리지: 86.95%
  * 구문 커버리지: 82.58%

**Comment by spartacontents** [comment]
### 커버리지 결과

  * 라인 커버리지: 82.58%
  * 브랜치 커버리지: 92.39%
  * 함수 커버리지: 86.95%
  * 구문 커버리지: 82.58%

**Comment by spartacontents** [comment]
### 커버리지 결과

  * 라인 커버리지: 82.58%
  * 브랜치 커버리지: 92.39%
  * 함수 커버리지: 86.95%
  * 구문 커버리지: 82.58%

**Comment by spartacontents** [comment]
### 커버리지 결과

  * 라인 커버리지: 82.58%
  * 브랜치 커버리지: 92.39%
  * 함수 커버리지: 86.95%
  * 구문 커버리지: 82.58%

**Comment by spartacontents** [comment]
### 커버리지 결과

  * 라인 커버리지: 82.58%
  * 브랜치 커버리지: 92.39%
  * 함수 커버리지: 86.95%
  * 구문 커버리지: 82.58%

**Comment by spartacontents** [comment]
### 커버리지 결과

  * 라인 커버리지: 82.58%
  * 브랜치 커버리지: 92.39%
  * 함수 커버리지: 86.95%
  * 구문 커버리지: 82.58%

**Comment by spartacontents** [comment]
### 커버리지 결과

  * 라인 커버리지: 82.58%
  * 브랜치 커버리지: 92.39%
  * 함수 커버리지: 86.95%
  * 구문 커버리지: 82.58%

**Comment by spartacontents** [comment]
### 커버리지 결과

  * 라인 커버리지: 82.58%
  * 브랜치 커버리지: 92.39%
  * 함수 커버리지: 86.95%
  * 구문 커버리지: 82.58%

**Comment by spartacontents** [comment]
### 커버리지 결과

  * 라인 커버리지: 82.58%
  * 브랜치 커버리지: 92.39%
  * 함수 커버리지: 86.95%
  * 구문 커버리지: 82.58%

**Comment by spartacontents** [comment]
⚡️ Lighthouse report!
| Category | Score |
| --- | --- |
| 🟠 Performance | 75 |
| 🟠 Accessibility | 84 |
| 🟢 Best Practices | 96 |
| 🟠 SEO | 82 |

⚡️ Lighthouse report!
| Category | Score |
| --- | --- |
| 🟢 Performance | 97 |
| 🟠 Accessibility | 84 |
| 🟢 Best Practices | 100 |
| 🟠 SEO | 82 |

⚡️ Lighthouse report!
| Category | Score |
| --- | --- |
| 🟢 Performance | 97 |
| 🟠 Accessibility | 84 |
| 🟢 Best Practices | 100 |
| 🟠 SEO | 82 |

**Review by jung-han — APPROVED** [review]
고생하셨어요~

**Pull request merged**
